name: bioseq
channels:
  - bioconda
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - default
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aria2=1.37.0=hbc8128a_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - codonw=1.4.4=h7b50bb2_7
  - cuda-version=12.8=h5d125a7_3
  - gawk=5.3.1=hcd3d067_0
  - git-lfs=3.7.0=h59e48b9_0
  - gmp=6.3.0=hac33072_2
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libasprintf=0.23.1=h8e693c7_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h81593ed_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mmseqs2=17.b804f=hd6d6fdc_1
  - mpfr=4.2.1=h90cbb55_3
  - nccl=2.26.2.1=ha44e49d_1
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - anndata==0.9.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.2
      - appdirs==1.4.4
      - argcomplete==3.6.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.3.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bio==1.6.2
      - biopython==1.83
      - biothings-client==0.3.1
      - bleach==6.1.0
      - boto==2.49.0
      - cachetools==5.5.0
      - catboost==1.2.7
      - certifi==2022.12.7
      - cffi==1.17.1
      - chanfig==0.0.111
      - charset-normalizer==2.1.1
      - clarabel==0.9.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.6
      - codon-bias==0.3.5
      - codonw-slim==1.5.0.post1
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==43.0.3
      - cvxpy==1.5.2
      - cycler==0.12.1
      - cython==3.0.12
      - danling==0.3.13
      - dask==2023.5.0
      - datasets==3.1.0
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dgllife==0.3.2
      - dill==0.3.6
      - disembl==2.0rc0
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.0
      - evo-model==0.4
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fair-esm==2.0.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flash-attn==2.7.0.post2
      - flatbuffers==24.3.25
      - fonttools==4.55.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gast==0.4.0
      - gcs-oauth2-boto-plugin==3.2
      - gdown==5.2.0
      - gensim==4.3.3
      - get-annotations==0.1.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glove-python-binary==0.2.0
      - google-apitools==0.5.32
      - google-auth==2.17.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - google-reauth==0.1.1
      - gprofiler-official==1.0.0
      - grpcio==1.68.1
      - gsutil==5.34
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - h5py==3.11.0
      - hf-xet==1.1.10
      - httpcore==1.0.7
      - httplib2==0.20.4
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - hydra==2.5
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - idna==3.4
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - import-ipynb==0.2
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - inquirerpy==0.3.4
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.3
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==2.13.1
      - kiwisolver==1.4.7
      - lazy-imports==0.3.1
      - learn2learn==0.2.0
      - libclang==18.1.1
      - lightgbm==4.5.0
      - lightning-utilities==0.11.9
      - lit==18.1.8
      - llvmlite==0.41.1
      - locket==1.0.0
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdtraj==1.10.0
      - mistune==3.0.2
      - ml-collections==0.1.1
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.1.0
      - multimolecule==0.0.7
      - multiprocess==0.70.14
      - mygene==3.2.2
      - natsort==8.4.0
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ncbi-genome-download==0.3.3
      - nest-asyncio==1.6.0
      - networkx==3.0
      - nibabel==5.2.1
      - notebook==7.3.1
      - notebook-shim==0.2.4
      - numba==0.58.1
      - numpy==1.24.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnxruntime==1.12.0
      - openfold==1.0.1
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - osqp==1.0.4
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.2
      - pandarallel==1.6.5
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.1
      - patsy==1.0.1
      - peft==0.13.2
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pluggy==1.5.0
      - pooch==1.8.2
      - portalocker==3.0.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==4.25.5
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py4j==0.10.9.9
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==3.0.3
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pynvml==11.5.3
      - pyopenssl==24.2.1
      - pyparsing==3.1.4
      - pypdf2==3.0.1
      - pyronn==0.1.0
      - pyronn-layers==0.1.4.1
      - pysocks==1.7.1
      - pytest==8.3.4
      - python-codon-tables==0.1.13
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-graphviz==0.20.3
      - python-json-logger==3.2.1
      - pytorch-lamb==1.0.0
      - pytorch-lightning==2.0.4
      - pytz==2024.2
      - pyu2f==0.1.5
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - qpth==0.0.18
      - rdkit==2024.3.5
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - responses==0.18.0
      - retry-decorator==1.1.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rotary-embedding-torch==0.8.6
      - rpds-py==0.20.1
      - rsa==4.7.2
      - safetensors==0.4.5
      - scanpy==1.9.8
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - selenium==4.27.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - session-info==1.0.0
      - setproctitle==1.3.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - strenum==0.4.15
      - stripedhyena==0.2.2
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torcheval==0.0.7
      - torchmetrics==1.5.2
      - torchsummary==1.5.1
      - torchvision==0.19.1+cu121
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - tree==0.2.4
      - trio==0.27.0
      - trio-websocket==0.11.1
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.0
      - tzdata==2024.2
      - umap-learn==0.5.7
      - unimol-tools==0.1.4.post1
      - upsetplot==0.9.0
      - uri-template==1.3.0
      - urllib3==1.26.13
      - viennarna==2.7.0
      - wandb==0.19.6
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webdriver-manager==4.0.2
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - wrapt==1.17.0
      - wsproto==1.2.0
      - xformers==0.0.28.post1
      - xgboost==2.1.3
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /hpcfs/fhome/yangchh/software/anaconda/envs/bioseq
